<a href="https://colab.research.google.com/github/UKD1211/Tier_N_Supplier_Visibility_Risk_Pred/blob/main/state_wise_risk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [203]:
import pandas as pd
import numpy as np

In [204]:
df = pd.read_csv("/content/Unemployment_rate.csv")

In [205]:
df.drop(columns = ['Sl. No.', '2019-20', '2020-21'], inplace = True)

In [206]:
df

                       State/UT  2021-22  2022-23  2023-24
0                Andhra Pradesh      4.2      4.1      4.1
1             Arunachal Pradesh      7.7      4.8      6.1
2                         Assam      3.8      1.7      3.9
3                         Bihar      6.0      3.9      3.0
4                  Chhattisgarh      2.5      2.5      2.5
5                         Delhi      5.3      1.9      2.1
6                           Goa     12.0      9.7      8.5
7                       Gujarat      2.0      1.7      1.1
8                       Haryana      9.0      6.1      3.4
9              Himachal Pradesh      4.0      4.4      5.4
10                    Jharkhand      2.0      1.7      1.3
11                    Karnataka      3.2      2.4      2.7
12                       Kerala      9.6      7.0      7.2
13               Madhya Pradesh      2.1      1.6      0.9
14                  Maharashtra      3.5      3.1      3.3
15                      Manipur      9.0      4.7      6.1
16                    Meghalaya      2.6      6.0      6.2
17                      Mizoram      5.4      2.2      2.3
18                     Nagaland      9.1      4.3      7.1
19                       Odisha      6.0      3.9      3.1
20                       Punjab      6.4      6.1      5.5
21                    Rajasthan      4.7      4.4      4.2
22                       Sikkim      1.6      2.2      2.3
23                   Tamil Nadu      4.8      4.3      3.5
24                    Telangana      4.2      4.4      4.8
25                      Tripura      3.3      1.4      1.7
26                  Uttarakhand      7.8      4.5      4.3
27                Uttar Pradesh      2.9      2.4      3.0
28                  West Bengal      3.5      2.2      2.6
29  Andaman and Nicobar Islands      7.8      9.7     11.8
30                   Chandigarh      6.3      4.0      7.1
31       Dadra and Nagar Haveli      5.2      2.5      2.3
32                Daman and Diu      NaN      NaN      NaN
33            Jammu and Kashmir      5.2      4.4      6.1
34                       Ladakh      3.3      6.1      5.1
35                  Lakshadweep     17.2     11.1     11.9
36                   Puducherry      5.8      5.6      4.6
37                    All India      4.1      3.2      3.2

In [207]:
df['avg_unemployment_rate'] = (df['2021-22'] + df['2022-23'] + df['2023-24'])/3

In [208]:
df

,State/UT,2021-22,2022-23,2023-24,avg_unemployment_rate
0,Andhra Pradesh,4.2,4.1,4.1,4.133333
1,Arunachal Pradesh,7.7,4.8,6.1,6.200000
2,Assam,3.8,1.7,3.9,3.133333
3,Bihar,6.0,3.9,3.0,4.300000
4,Chhattisgarh,2.5,2.5,2.5,2.500000
5,Delhi,5.3,1.9,2.1,3.100000
6,Goa,12.0,9.7,8.5,10.066667
7,Gujarat,2.0,1.7,1.1,1.600000
8,Haryana,9.0,6.1,3.4,6.166667
9,Himachal Pradesh,4.0,4.4,5.4,4.600000
10,Jharkhand,2.0,1.7,1.3,1.666667
11,Karnataka,3.2,2.4,2.7,2.766667
12,Kerala,9.6,7.0,7.2,7.933333
13,Madhya Pradesh,2.1,1.6,0.9,1.533333
14,Maharashtra,3.5,3.1,3.3,3.300000
15,Manipur,9.0,4.7,6.1,6.600000
16,Meghalaya,2.6,6.0,6.2,4.933333
17,Mizoram,5.4,2.2,2.3,3.300000
18,Nagaland,9.1,4.3,7.1,6.833333
19,Odisha,6.0,3.9,3.1,4.333333
20,Punjab,6.4,6.1,5.5,6.000000
21,Rajasthan,4.7,4.4,4.2,4.433333
22,Sikkim,1.6,2.2,2.3,2.033333
23,Tamil Nadu,4.8,4.3,3.5,4.200000
24,Telangana,4.2,4.4,4.8,4.466667
25,Tripura,3.3,1.4,1.7,2.133333
26,Uttarakhand,7.8,4.5,4.3,5.533333
27,Uttar Pradesh,2.9,2.4,3.0,2.766667
28,West Bengal,3.5,2.2,2.6,2.766667
29,Andaman and Nicobar Islands,7.8,9.7,11.8,9.766667
30,Chandigarh,6.3,4.0,7.1,5.800000
31,Dadra and Nagar Haveli,5.2,2.5,2.3,3.333333
32,Daman and Diu,NaN,NaN,NaN,NaN
33,Jammu and Kashmir,5.2,4.4,6.1,5.233333
34,Ladakh,3.3,6.1,5.1,4.833333
35,Lakshadweep,17.2,11.1,11.9,13.400000
36,Puducherry,5.8,5.6,4.6,5.333333
37,All India,4.1,3.2,3.2,3.500000

In [209]:
df_unemployment_rate = df[['State/UT', 'avg_unemployment_rate']]

In [210]:
df_unemployment_rate = df_unemployment_rate.iloc[0:37,:]

In [211]:
df_unemployment_rate = df_unemployment_rate.sort_values(by= 'State/UT').reset_index().drop(columns = ['index'])

In [212]:
#inflation

In [213]:
df_2 = pd.read_csv("/content/state_wise_inflation_rate.csv", header=1)

In [214]:
df_2

,Year,Month,State,Group,Sub Group,Description,Rural,Urban,Combined,Status,Unnamed: 10
0,2022,January,Andaman and Nicobar Islands,NaN,NaN,General Index (All Groups),8.32,6.26,7.36,F,NaN
1,2022,January,Andhra Pradesh,NaN,NaN,General Index (All Groups),4.69,5.78,5.12,F,NaN
2,2022,January,Arunachal Pradesh,NaN,NaN,General Index (All Groups),6.35,NaN,NaN,F,NaN
3,2022,January,Assam,NaN,NaN,General Index (All Groups),5.81,3.86,5.43,F,NaN
4,2022,January,Bihar,NaN,NaN,General Index (All Groups),5.60,6.21,5.71,F,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1327,2025,January,Telangana,NaN,NaN,General Index (All Groups),2.34,2.15,2.22,F,NaN
1328,2025,January,Tripura,NaN,NaN,General Index (All Groups),2.44,3.57,2.71,F,NaN
1329,2025,January,Uttar Pradesh,NaN,NaN,General Index (All Groups),5.07,3.74,4.59,F,NaN
1330,2025,January,Uttarakhand,NaN,NaN,General Index (All Groups),4.37,5.67,4.90,F,NaN
1331,2025,January,West Bengal,NaN,NaN,General Index (All Groups),3.77,2.93,3.38,F,NaN

In [215]:
df_2.drop(columns = ['Group','Sub Group', 'Rural', 'Urban', 'Status', 'Unnamed: 10','Description'], inplace = True)

In [216]:
df_2

      Year    Month                        State  Combined
0     2022  January  Andaman and Nicobar Islands      7.36
1     2022  January               Andhra Pradesh      5.12
2     2022  January            Arunachal Pradesh       NaN
3     2022  January                        Assam      5.43
4     2022  January                        Bihar      5.71
...    ...      ...                          ...       ...
1327  2025  January                    Telangana      2.22
1328  2025  January                      Tripura      2.71
1329  2025  January                Uttar Pradesh      4.59
1330  2025  January                  Uttarakhand      4.90
1331  2025  January                  West Bengal      3.38

[1332 rows x 4 columns]

In [217]:
df_2['State'].value_counts().shape

(36,)

In [218]:
df_2.groupby('State')['Combined'].mean().sort_values(ascending = False)

State
Haryana                        6.639730
Telangana                      6.552162
Uttar Pradesh                  6.295405
Odisha                         6.275405
Dadra and Nagar Haveli         6.226486
Rajasthan                      6.096486
Bihar                          6.024054
Andhra Pradesh                 5.989730
Tripura                        5.931351
Gujarat                        5.902973
Madhya Pradesh                 5.776216
Maharashtra                    5.734865
Manipur                        5.637027
Uttarakhand                    5.594865
Assam                          5.580270
Jharkhand                      5.514324
West Bengal                    5.483514
Karnataka                      5.478378
Mizoram                        5.473784
Puducherry                     5.438378
Kerala                         5.374865
Tamil Nadu                     5.370541
Punjab                         5.258649
Daman and Diu                  5.246757
Jammu and Kashmir              5.205946
Chandigarh                     4.957297
Chhattisgarh                   4.777297
Himachal Pradesh               4.758919
Sikkim                         4.630541
Nagaland                       4.514324
Andaman and Nicobar Islands    4.388108
Lakshadweep                    4.344595
Meghalaya                      4.069189
Delhi                          3.298108
Goa                            3.192162
Arunachal Pradesh                   NaN
Name: Combined, dtype: float64

In [219]:
df_inflation = df_2.groupby('State')['Combined'].mean().reset_index()

In [220]:
df_inflation

                          State  Combined
0   Andaman and Nicobar Islands  4.388108
1                Andhra Pradesh  5.989730
2             Arunachal Pradesh       NaN
3                         Assam  5.580270
4                         Bihar  6.024054
5                    Chandigarh  4.957297
6                  Chhattisgarh  4.777297
7        Dadra and Nagar Haveli  6.226486
8                 Daman and Diu  5.246757
9                         Delhi  3.298108
10                          Goa  3.192162
11                      Gujarat  5.902973
12                      Haryana  6.639730
13             Himachal Pradesh  4.758919
14            Jammu and Kashmir  5.205946
15                    Jharkhand  5.514324
16                    Karnataka  5.478378
17                       Kerala  5.374865
18                  Lakshadweep  4.344595
19               Madhya Pradesh  5.776216
20                  Maharashtra  5.734865
21                      Manipur  5.637027
22                    Meghalaya  4.069189
23                      Mizoram  5.473784
24                     Nagaland  4.514324
25                       Odisha  6.275405
26                   Puducherry  5.438378
27                       Punjab  5.258649
28                    Rajasthan  6.096486
29                       Sikkim  4.630541
30                   Tamil Nadu  5.370541
31                    Telangana  6.552162
32                      Tripura  5.931351
33                Uttar Pradesh  6.295405
34                  Uttarakhand  5.594865
35                  West Bengal  5.483514

In [221]:
df_inflation.rename(columns={'Combined': 'inflation_rate'}, inplace=True)

In [222]:
df_inflation

                          State  inflation_rate
0   Andaman and Nicobar Islands        4.388108
1                Andhra Pradesh        5.989730
2             Arunachal Pradesh             NaN
3                         Assam        5.580270
4                         Bihar        6.024054
5                    Chandigarh        4.957297
6                  Chhattisgarh        4.777297
7        Dadra and Nagar Haveli        6.226486
8                 Daman and Diu        5.246757
9                         Delhi        3.298108
10                          Goa        3.192162
11                      Gujarat        5.902973
12                      Haryana        6.639730
13             Himachal Pradesh        4.758919
14            Jammu and Kashmir        5.205946
15                    Jharkhand        5.514324
16                    Karnataka        5.478378
17                       Kerala        5.374865
18                  Lakshadweep        4.344595
19               Madhya Pradesh        5.776216
20                  Maharashtra        5.734865
21                      Manipur        5.637027
22                    Meghalaya        4.069189
23                      Mizoram        5.473784
24                     Nagaland        4.514324
25                       Odisha        6.275405
26                   Puducherry        5.438378
27                       Punjab        5.258649
28                    Rajasthan        6.096486
29                       Sikkim        4.630541
30                   Tamil Nadu        5.370541
31                    Telangana        6.552162
32                      Tripura        5.931351
33                Uttar Pradesh        6.295405
34                  Uttarakhand        5.594865
35                  West Bengal        5.483514

In [223]:
df_unemployment_rate.dropna(inplace = True)

In [224]:
df_unemployment_rate

                       State/UT  avg_unemployment_rate
0   Andaman and Nicobar Islands               9.766667
1                Andhra Pradesh               4.133333
2             Arunachal Pradesh               6.200000
3                         Assam               3.133333
4                         Bihar               4.300000
5                    Chandigarh               5.800000
6                  Chhattisgarh               2.500000
7        Dadra and Nagar Haveli               3.333333
9                         Delhi               3.100000
10                          Goa              10.066667
11                      Gujarat               1.600000
12                      Haryana               6.166667
13             Himachal Pradesh               4.600000
14            Jammu and Kashmir               5.233333
15                    Jharkhand               1.666667
16                    Karnataka               2.766667
17                       Kerala               7.933333
18                       Ladakh               4.833333
19                  Lakshadweep              13.400000
20               Madhya Pradesh               1.533333
21                  Maharashtra               3.300000
22                      Manipur               6.600000
23                    Meghalaya               4.933333
24                      Mizoram               3.300000
25                     Nagaland               6.833333
26                       Odisha               4.333333
27                   Puducherry               5.333333
28                       Punjab               6.000000
29                    Rajasthan               4.433333
30                       Sikkim               2.033333
31                   Tamil Nadu               4.200000
32                    Telangana               4.466667
33                      Tripura               2.133333
34                Uttar Pradesh               2.766667
35                  Uttarakhand               5.533333
36                  West Bengal               2.766667

In [225]:
#poverty_index

In [226]:
df_3 = pd.read_excel("/content/poverty_index.XLSX")

In [227]:
df_3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,TABLE 10: STATE-WISE POVERTY ESTIMATES - MULTI...,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,State/Union Territory,NFHS-4 (2015-16),NaN,NaN,NFHS-5 (2019-21),NaN,NaN
2,NaN,NaN,Headcount Ratio (Per cent),Intensity (Per cent),MPI,Headcount Ratio (Per cent),Intensity (Per cent),MPI
3,NaN,Andhra Pradesh,11.77,43.28,0.05,6.06,41.12,0.03
4,NaN,Arunachal Pradesh,24.23,47.25,0.12,13.76,43.04,0.06
5,NaN,Assam,32.65,47.88,0.16,19.35,44.41,0.09
6,NaN,Bihar,51.89,51.01,0.27,33.76,47.4,0.16
7,NaN,Chhattisgarh,29.9,44.64,0.13,16.37,42.61,0.07
8,NaN,Goa,3.76,40.13,0.02,0.84,38.69,0
9,NaN,Gujarat,18.47,44.97,0.08,11.66,43.25,0.05
10,NaN,Haryana,11.88,44.4,0.05,7.07,43.34,0.03
11,NaN,Himachal Pradesh,7.59,39.44,0.03,4.93,40.22,0.02
12,NaN,Jharkhand,42.1,47.92,0.2,28.81,45.59,0.13
13,NaN,Karnataka,12.77,42.76,0.06,7.58,41.21,0.03
14,NaN,Kerala,0.7,38.99,0,0.55,36.92,0
15,NaN,Madhya Pradesh,36.57,47.25,0.17,20.63,43.7,0.09
16,NaN,Maharashtra,14.8,43.76,0.07,7.81,41.77,0.03
17,NaN,Manipur,16.96,44.61,0.08,8.1,41.91,0.03
18,NaN,Meghalaya,32.54,48.08,0.16,27.79,48.01,0.13
19,NaN,Mizoram,9.78,47.42,0.05,5.3,45.62,0.02
20,NaN,Nagaland,25.16,46.29,0.12,15.43,42.61,0.07
21,NaN,Odisha,29.34,46.42,0.14,15.68,44.5,0.07
22,NaN,Punjab,5.57,43.74,0.02,4.75,41.22,0.02
23,NaN,Rajasthan,28.86,47.34,0.14,15.31,42.7,0.07
24,NaN,Sikkim,3.82,41.2,0.02,2.6,41.02,0.01
25,NaN,Tamil Nadu,4.76,39.97,0.02,2.2,38.7,0.01
26,NaN,Telangana,13.18,43.29,0.06,5.88,40.85,0.02
27,NaN,Tripura,16.62,45.03,0.08,13.11,42.68,0.06
28,NaN,Uttar Pradesh,37.68,47.6,0.18,22.93,44.83,0.1
29,NaN,Uttarakhand,17.67,44.35,0.08,9.67,41.99,0.04
30,NaN,West Bengal,21.29,45.5,0.1,11.89,42.35,0.05
31,NaN,Andaman & Nicobar Islands,4.29,40.5,0.02,2.3,40.62,0.01
32,NaN,Chandigarh,5.97,43.39,0.03,3.52,47.41,0.02
33,NaN,Dadra & Nagar Haveli & Daman & Diu,19.58,44.23,0.09,9.21,42.15,0.04
34,NaN,Delhi,4.44,43.92,0.02,3.43,41.99,0.01
35,NaN,Jammu & Kashmir,12.56,44.17,0.06,4.8,42.11,0.02
36,NaN,Ladakh,12.7,40.37,0.05,3.53,41.2,0.02
37,NaN,Lakshadweep,1.82,35.8,0.01,1.11,36.47,0
38,NaN,Puducherry,1.71,38.55,0.01,0.85,38.03,0
39,NaN,ALL INDIA,24.85,47.14,0.12,14.96,44.39,0.07
40,NaN,NFHS: National Family Health Survey. MPI: Mult...,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,Source: NITI Aayog (National Multi-dimensional...,NaN,NaN,NaN,NaN,NaN,NaN

In [228]:
df_3 = df_3.iloc[3:].reset_index(drop=True)

In [229]:
df_3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Andhra Pradesh,11.77,43.28,0.05,6.06,41.12,0.03
1,NaN,Arunachal Pradesh,24.23,47.25,0.12,13.76,43.04,0.06
2,NaN,Assam,32.65,47.88,0.16,19.35,44.41,0.09
3,NaN,Bihar,51.89,51.01,0.27,33.76,47.4,0.16
4,NaN,Chhattisgarh,29.9,44.64,0.13,16.37,42.61,0.07
5,NaN,Goa,3.76,40.13,0.02,0.84,38.69,0
6,NaN,Gujarat,18.47,44.97,0.08,11.66,43.25,0.05
7,NaN,Haryana,11.88,44.4,0.05,7.07,43.34,0.03
8,NaN,Himachal Pradesh,7.59,39.44,0.03,4.93,40.22,0.02
9,NaN,Jharkhand,42.1,47.92,0.2,28.81,45.59,0.13
10,NaN,Karnataka,12.77,42.76,0.06,7.58,41.21,0.03
11,NaN,Kerala,0.7,38.99,0,0.55,36.92,0
12,NaN,Madhya Pradesh,36.57,47.25,0.17,20.63,43.7,0.09
13,NaN,Maharashtra,14.8,43.76,0.07,7.81,41.77,0.03
14,NaN,Manipur,16.96,44.61,0.08,8.1,41.91,0.03
15,NaN,Meghalaya,32.54,48.08,0.16,27.79,48.01,0.13
16,NaN,Mizoram,9.78,47.42,0.05,5.3,45.62,0.02
17,NaN,Nagaland,25.16,46.29,0.12,15.43,42.61,0.07
18,NaN,Odisha,29.34,46.42,0.14,15.68,44.5,0.07
19,NaN,Punjab,5.57,43.74,0.02,4.75,41.22,0.02
20,NaN,Rajasthan,28.86,47.34,0.14,15.31,42.7,0.07
21,NaN,Sikkim,3.82,41.2,0.02,2.6,41.02,0.01
22,NaN,Tamil Nadu,4.76,39.97,0.02,2.2,38.7,0.01
23,NaN,Telangana,13.18,43.29,0.06,5.88,40.85,0.02
24,NaN,Tripura,16.62,45.03,0.08,13.11,42.68,0.06
25,NaN,Uttar Pradesh,37.68,47.6,0.18,22.93,44.83,0.1
26,NaN,Uttarakhand,17.67,44.35,0.08,9.67,41.99,0.04
27,NaN,West Bengal,21.29,45.5,0.1,11.89,42.35,0.05
28,NaN,Andaman & Nicobar Islands,4.29,40.5,0.02,2.3,40.62,0.01
29,NaN,Chandigarh,5.97,43.39,0.03,3.52,47.41,0.02
30,NaN,Dadra & Nagar Haveli & Daman & Diu,19.58,44.23,0.09,9.21,42.15,0.04
31,NaN,Delhi,4.44,43.92,0.02,3.43,41.99,0.01
32,NaN,Jammu & Kashmir,12.56,44.17,0.06,4.8,42.11,0.02
33,NaN,Ladakh,12.7,40.37,0.05,3.53,41.2,0.02
34,NaN,Lakshadweep,1.82,35.8,0.01,1.11,36.47,0
35,NaN,Puducherry,1.71,38.55,0.01,0.85,38.03,0
36,NaN,ALL INDIA,24.85,47.14,0.12,14.96,44.39,0.07
37,NaN,NFHS: National Family Health Survey. MPI: Mult...,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,Source: NITI Aayog (National Multi-dimensional...,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
df_3.columns = [
    "drop",
    "State",
    "NFHS4_headcount",
    "NFHS4_intensity",
    "NFHS4_MPI",
    "NFHS5_headcount",
    "NFHS5_intensity",
    "NFHS5_MPI"
]

In [231]:
df_3 = df_3[["State", "NFHS5_MPI"]]

In [232]:
df_3["State"] = df_3["State"].str.strip()

/tmp/ipykernel_3714/1167422776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3["State"] = df_3["State"].str.strip()

In [233]:
df_3["NFHS5_MPI"] = pd.to_numeric(df_3["NFHS5_MPI"], errors="coerce")

/tmp/ipykernel_3714/2043118937.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3["NFHS5_MPI"] = pd.to_numeric(df_3["NFHS5_MPI"], errors="coerce")

In [234]:
df_3 = df_3.dropna()

In [235]:
df_3.rename(columns={"NFHS5_MPI": "poverty_rate"}, inplace=True)

In [236]:
df_3 = df_3.sort_values(by="State").reset_index(drop=True)

In [237]:
df_poverty_rate = df_3[1:].reset_index(drop = True)

In [238]:
df_poverty_rate

                                 State  poverty_rate
0            Andaman & Nicobar Islands          0.01
1                       Andhra Pradesh          0.03
2                    Arunachal Pradesh          0.06
3                                Assam          0.09
4                                Bihar          0.16
5                           Chandigarh          0.02
6                         Chhattisgarh          0.07
7   Dadra & Nagar Haveli & Daman & Diu          0.04
8                                Delhi          0.01
9                                  Goa          0.00
10                             Gujarat          0.05
11                             Haryana          0.03
12                    Himachal Pradesh          0.02
13                     Jammu & Kashmir          0.02
14                           Jharkhand          0.13
15                           Karnataka          0.03
16                              Kerala          0.00
17                              Ladakh          0.02
18                         Lakshadweep          0.00
19                      Madhya Pradesh          0.09
20                         Maharashtra          0.03
21                             Manipur          0.03
22                           Meghalaya          0.13
23                             Mizoram          0.02
24                            Nagaland          0.07
25                              Odisha          0.07
26                          Puducherry          0.00
27                              Punjab          0.02
28                           Rajasthan          0.07
29                              Sikkim          0.01
30                          Tamil Nadu          0.01
31                           Telangana          0.02
32                             Tripura          0.06
33                       Uttar Pradesh          0.10
34                         Uttarakhand          0.04
35                         West Bengal          0.05

In [239]:
#per_capita_income

In [240]:
df_4 = pd.read_excel("/content/per_capita_income.xlsx")

In [241]:
df_4

,TABLE 19: PER CAPITA NET STATE DOMESTIC PRODUCT (Current Prices) (Concld.),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,(₹),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,State/Union Territory,Base: 2011-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2017-18,2018-19,2019-20,2020-21,2021-22,2022-23,2023-24,2024-25
3,Andaman & Nicobar Islands,178709,204254,219653,205368,229570,263984,276000,-
4,Andhra Pradesh,138299,154031,160341,168063,193703,219917,237951,266240
5,Arunachal Pradesh,138836,155103,182171,181537,190851,204469,217325,246813
6,Assam,75151,81034,90123,86947,103371,121573,143852,159185
7,Bihar,36850,40715,44175,42128,47296,54637,62201,69321
8,Chandigarh,280512,307812,330703,290417,337406,408512,453457,-
9,Chhattisgarh,88793,102024,106611,106117,123493,134996,148922,162870
10,Delhi,318323,338730,355798,322311,370824,417217,459408,493024
11,Goa,411740,423716,435949,423047,459094,532854,585953,-
12,Gujarat,176961,197457,212428,207324,241584,272451,-,-
13,Haryana,208437,223022,232530,225137,265163,289213,319363,353182
14,Himachal Pradesh,165497,174804,186559,173565,193016,214952,234721,256137
15,Jammu & Kashmir*,87710,98738,101868,101645,112898,123614,140051,154826
16,Jharkhand,67484,75421,75016,69963,88500,95839,106529,116663
17,Karnataka,185840,205245,222141,221683,268963,310325,339813,380906
18,Kerala,183252,205437,208879,194432,230280,257307,281269,308338
19,Ladakh,-,-,-,-,-,186970,242360,-
20,Madhya Pradesh,81966,92337,101909,101958,117402,127947,139713,152615
21,Maharashtra,172663,182865,189843,182454,219620,252289,278681,309340
22,Manipur,71507,73795,78574,75784,98826,107133,119938,-
23,Meghalaya,82457,88954,95422,90751,107971,124673,141195,157141
24,Mizoram,155222,164708,195365,173521,190965,213665,234996,-
25,Nagaland,102003,109198,122759,119781,127225,138889,154828,-
26,Odisha,87055,98005,104633,103211,133768,134612,150414,168966
27,Puducherry,198357,204140,217937,208862,231557,231231,252164,281478
28,Punjab,139835,149974,154385,150620,170276,185802,205374,221197
29,Rajasthan,98698,106604,115534,114925,134143,150020,166647,185053
30,Sikkim,349163,375773,412627,415045,466518,520466,587743,-
31,Tamil Nadu,175276,194373,206165,209628,242339,275272,313329,361619
32,Telangana,179358,209848,231326,225734,269000,312046,347714,387623
33,Tripura,100444,113016,121456,118401,137032,153584,172299,192842
34,Uttar Pradesh,59595,64113,67639,63464,76063,84640,97364,108572
35,Uttarakhand,180857,186207,190558,174526,194670,219850,246178,274064
36,West Bengal,91401,103920,110316,105108,122883,137909,149515,163467

In [242]:
df_4 = df_4.iloc[3:].reset_index(drop=True)

In [243]:
df_4.columns = [
    "State",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024"
]

In [244]:
df_4["State"] = df_4["State"].str.strip()

In [245]:
for col in df_4.columns[1:]:
    df_4[col] = pd.to_numeric(df_4[col], errors="coerce")

In [246]:
df_4["per_capita_income"] = df_4[["2021", "2022", "2023"]].mean(axis=1)

In [247]:
df_4 = df_4[["State", "per_capita_income"]]

In [248]:
df_4 = df_4.dropna()

In [249]:
df_4 = df_4.sort_values(by="State").reset_index(drop=True)

In [250]:
df_per_capita_income = df_4

In [251]:
df_per_capita_income

                        State  per_capita_income
0   Andaman & Nicobar Islands      256518.000000
1              Andhra Pradesh      217190.333333
2           Arunachal Pradesh      204215.000000
3                       Assam      122932.000000
4                       Bihar       54711.333333
5                  Chandigarh      399791.666667
6                Chhattisgarh      135803.666667
7                       Delhi      415816.333333
8                         Goa      525967.000000
9                     Gujarat      257017.500000
10                    Haryana      291246.333333
11           Himachal Pradesh      214229.666667
12           Jammu & Kashmir*      125521.000000
13                  Jharkhand       96956.000000
14                  Karnataka      306367.000000
15                     Kerala      256285.333333
16                     Ladakh      214665.000000
17             Madhya Pradesh      128354.000000
18                Maharashtra      250196.666667
19                    Manipur      108632.333333
20                  Meghalaya      124613.000000
21                    Mizoram      213208.666667
22                   Nagaland      140314.000000
23                     Odisha      139598.000000
24                 Puducherry      238317.333333
25                     Punjab      187150.666667
26                  Rajasthan      150270.000000
27                     Sikkim      524909.000000
28                 Tamil Nadu      276980.000000
29                  Telangana      309586.666667
30                    Tripura      154305.000000
31              Uttar Pradesh       86022.333333
32                Uttarakhand      220232.666667
33                West Bengal      136769.000000

In [252]:
df_unemp = df_unemployment_rate.merge(df_per_capita_income, left_on="State/UT", right_on="State", how="left") \
                               .drop(columns=["State"])

In [254]:
df_unemp.rename(columns={"State/UT": "State"}, inplace=True)
df_unemp

                          State  avg_unemployment_rate  per_capita_income
0   Andaman and Nicobar Islands               9.766667                NaN
1                Andhra Pradesh               4.133333      217190.333333
2             Arunachal Pradesh               6.200000      204215.000000
3                         Assam               3.133333      122932.000000
4                         Bihar               4.300000       54711.333333
5                    Chandigarh               5.800000      399791.666667
6                  Chhattisgarh               2.500000      135803.666667
7        Dadra and Nagar Haveli               3.333333                NaN
8                         Delhi               3.100000      415816.333333
9                           Goa              10.066667      525967.000000
10                      Gujarat               1.600000      257017.500000
11                      Haryana               6.166667      291246.333333
12             Himachal Pradesh               4.600000      214229.666667
13            Jammu and Kashmir               5.233333                NaN
14                    Jharkhand               1.666667       96956.000000
15                    Karnataka               2.766667      306367.000000
16                       Kerala               7.933333      256285.333333
17                       Ladakh               4.833333      214665.000000
18                  Lakshadweep              13.400000                NaN
19               Madhya Pradesh               1.533333      128354.000000
20                  Maharashtra               3.300000      250196.666667
21                      Manipur               6.600000      108632.333333
22                    Meghalaya               4.933333      124613.000000
23                      Mizoram               3.300000      213208.666667
24                     Nagaland               6.833333      140314.000000
25                       Odisha               4.333333      139598.000000
26                   Puducherry               5.333333      238317.333333
27                       Punjab               6.000000      187150.666667
28                    Rajasthan               4.433333      150270.000000
29                       Sikkim               2.033333      524909.000000
30                   Tamil Nadu               4.200000      276980.000000
31                    Telangana               4.466667      309586.666667
32                      Tripura               2.133333      154305.000000
33                Uttar Pradesh               2.766667       86022.333333
34                  Uttarakhand               5.533333      220232.666667
35                  West Bengal               2.766667      136769.000000

In [255]:
set(df_unemployment_rate["State/UT"]) - set(df_per_capita_income["State"])

{'Andaman and Nicobar Islands',
 'Dadra and Nagar Haveli',
 'Jammu and Kashmir',
 'Lakshadweep'}

In [256]:
state_map = {
    "Andaman and Nicobar Islands": "Andaman & Nicobar Islands",
    "Dadra and Nagar Haveli": "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi": "Delhi",
    "Jammu & Kashmir": "Jammu and Kashmir"
}

df_unemployment_rate["State/UT"] = df_unemployment_rate["State/UT"].replace(state_map)

In [257]:
df_unemp = df_unemployment_rate.merge(
    df_per_capita_income,
    left_on="State/UT",
    right_on="State",
    how="left"
).drop(columns=["State"])

df_unemp.rename(columns={"State/UT": "State"}, inplace=True)

In [258]:
df_unemp["per_capita_income"].fillna(df_unemp["per_capita_income"].mean(), inplace=True)

/tmp/ipykernel_3714/2604215634.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_unemp["per_capita_income"].fillna(df_unemp["per_capita_income"].mean(), inplace=True)

In [259]:
df_unemp

,State,avg_unemployment_rate,per_capita_income
0,Andaman & Nicobar Islands,9.766667,256518.000000
1,Andhra Pradesh,4.133333,217190.333333
2,Arunachal Pradesh,6.200000,204215.000000
3,Assam,3.133333,122932.000000
4,Bihar,4.300000,54711.333333
5,Chandigarh,5.800000,399791.666667
6,Chhattisgarh,2.500000,135803.666667
7,Dadra and Nagar Haveli and Daman and Diu,3.333333,223005.196970
8,Delhi,3.100000,415816.333333
9,Goa,10.066667,525967.000000
10,Gujarat,1.600000,257017.500000
11,Haryana,6.166667,291246.333333
12,Himachal Pradesh,4.600000,214229.666667
13,Jammu and Kashmir,5.233333,223005.196970
14,Jharkhand,1.666667,96956.000000
15,Karnataka,2.766667,306367.000000
16,Kerala,7.933333,256285.333333
17,Ladakh,4.833333,214665.000000
18,Lakshadweep,13.400000,223005.196970
19,Madhya Pradesh,1.533333,128354.000000
20,Maharashtra,3.300000,250196.666667
21,Manipur,6.600000,108632.333333
22,Meghalaya,4.933333,124613.000000
23,Mizoram,3.300000,213208.666667
24,Nagaland,6.833333,140314.000000
25,Odisha,4.333333,139598.000000
26,Puducherry,5.333333,238317.333333
27,Punjab,6.000000,187150.666667
28,Rajasthan,4.433333,150270.000000
29,Sikkim,2.033333,524909.000000
30,Tamil Nadu,4.200000,276980.000000
31,Telangana,4.466667,309586.666667
32,Tripura,2.133333,154305.000000
33,Uttar Pradesh,2.766667,86022.333333
34,Uttarakhand,5.533333,220232.666667
35,West Bengal,2.766667,136769.000000

In [260]:
for df in [df_unemployment_rate, df_per_capita_income]:
    df.iloc[:, 0] = df.iloc[:, 0].str.strip()

In [263]:
df_final = df_unemp.merge(df_inflation, left_on="State", right_on="State", how="left").merge(df_poverty_rate, left_on="State", right_on="State", how="left")

In [264]:
df_final

,State,avg_unemployment_rate,per_capita_income,inflation_rate,poverty_rate
0,Andaman & Nicobar Islands,9.766667,256518.000000,NaN,0.01
1,Andhra Pradesh,4.133333,217190.333333,5.989730,0.03
2,Arunachal Pradesh,6.200000,204215.000000,NaN,0.06
3,Assam,3.133333,122932.000000,5.580270,0.09
4,Bihar,4.300000,54711.333333,6.024054,0.16
5,Chandigarh,5.800000,399791.666667,4.957297,0.02
6,Chhattisgarh,2.500000,135803.666667,4.777297,0.07
7,Dadra and Nagar Haveli and Daman and Diu,3.333333,223005.196970,NaN,NaN
8,Delhi,3.100000,415816.333333,3.298108,0.01
9,Goa,10.066667,525967.000000,3.192162,0.00
10,Gujarat,1.600000,257017.500000,5.902973,0.05
11,Haryana,6.166667,291246.333333,6.639730,0.03
12,Himachal Pradesh,4.600000,214229.666667,4.758919,0.02
13,Jammu and Kashmir,5.233333,223005.196970,5.205946,NaN
14,Jharkhand,1.666667,96956.000000,5.514324,0.13
15,Karnataka,2.766667,306367.000000,5.478378,0.03
16,Kerala,7.933333,256285.333333,5.374865,0.00
17,Ladakh,4.833333,214665.000000,NaN,0.02
18,Lakshadweep,13.400000,223005.196970,4.344595,0.00
19,Madhya Pradesh,1.533333,128354.000000,5.776216,0.09
20,Maharashtra,3.300000,250196.666667,5.734865,0.03
21,Manipur,6.600000,108632.333333,5.637027,0.03
22,Meghalaya,4.933333,124613.000000,4.069189,0.13
23,Mizoram,3.300000,213208.666667,5.473784,0.02
24,Nagaland,6.833333,140314.000000,4.514324,0.07
25,Odisha,4.333333,139598.000000,6.275405,0.07
26,Puducherry,5.333333,238317.333333,5.438378,0.00
27,Punjab,6.000000,187150.666667,5.258649,0.02
28,Rajasthan,4.433333,150270.000000,6.096486,0.07
29,Sikkim,2.033333,524909.000000,4.630541,0.01
30,Tamil Nadu,4.200000,276980.000000,5.370541,0.01
31,Telangana,4.466667,309586.666667,6.552162,0.02
32,Tripura,2.133333,154305.000000,5.931351,0.06
33,Uttar Pradesh,2.766667,86022.333333,6.295405,0.10
34,Uttarakhand,5.533333,220232.666667,5.594865,0.04
35,West Bengal,2.766667,136769.000000,5.483514,0.05

In [265]:
df_final.isnull().mean()

State                    0.000000
avg_unemployment_rate    0.000000
per_capita_income        0.000000
inflation_rate           0.111111
poverty_rate             0.055556
dtype: float64

In [266]:
set(df_unemp["State"]) - set(df_inflation["State"])

{'Andaman & Nicobar Islands',
 'Dadra and Nagar Haveli and Daman and Diu',
 'Ladakh'}

In [267]:
state_map = {
    "Andaman & Nicobar Islands": "Andaman and Nicobar Islands",
    "Dadra and Nagar Haveli and Daman and Diu": "Dadra and Nagar Haveli",
}

for df in [df_inflation, df_poverty_rate]:
    df["State"] = df["State"].replace(state_map)

In [268]:
for col in ["inflation_rate", "poverty_rate", "per_capita_income"]:
    df_final[col].fillna(df_final[col].median(), inplace=True)

/tmp/ipykernel_3714/1558809023.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final[col].fillna(df_final[col].median(), inplace=True)

In [269]:
df_final

,State,avg_unemployment_rate,per_capita_income,inflation_rate,poverty_rate
0,Andaman & Nicobar Islands,9.766667,256518.000000,5.480946,0.01
1,Andhra Pradesh,4.133333,217190.333333,5.989730,0.03
2,Arunachal Pradesh,6.200000,204215.000000,5.480946,0.06
3,Assam,3.133333,122932.000000,5.580270,0.09
4,Bihar,4.300000,54711.333333,6.024054,0.16
5,Chandigarh,5.800000,399791.666667,4.957297,0.02
6,Chhattisgarh,2.500000,135803.666667,4.777297,0.07
7,Dadra and Nagar Haveli and Daman and Diu,3.333333,223005.196970,5.480946,0.03
8,Delhi,3.100000,415816.333333,3.298108,0.01
9,Goa,10.066667,525967.000000,3.192162,0.00
10,Gujarat,1.600000,257017.500000,5.902973,0.05
11,Haryana,6.166667,291246.333333,6.639730,0.03
12,Himachal Pradesh,4.600000,214229.666667,4.758919,0.02
13,Jammu and Kashmir,5.233333,223005.196970,5.205946,0.03
14,Jharkhand,1.666667,96956.000000,5.514324,0.13
15,Karnataka,2.766667,306367.000000,5.478378,0.03
16,Kerala,7.933333,256285.333333,5.374865,0.00
17,Ladakh,4.833333,214665.000000,5.480946,0.02
18,Lakshadweep,13.400000,223005.196970,4.344595,0.00
19,Madhya Pradesh,1.533333,128354.000000,5.776216,0.09
20,Maharashtra,3.300000,250196.666667,5.734865,0.03
21,Manipur,6.600000,108632.333333,5.637027,0.03
22,Meghalaya,4.933333,124613.000000,4.069189,0.13
23,Mizoram,3.300000,213208.666667,5.473784,0.02
24,Nagaland,6.833333,140314.000000,4.514324,0.07
25,Odisha,4.333333,139598.000000,6.275405,0.07
26,Puducherry,5.333333,238317.333333,5.438378,0.00
27,Punjab,6.000000,187150.666667,5.258649,0.02
28,Rajasthan,4.433333,150270.000000,6.096486,0.07
29,Sikkim,2.033333,524909.000000,4.630541,0.01
30,Tamil Nadu,4.200000,276980.000000,5.370541,0.01
31,Telangana,4.466667,309586.666667,6.552162,0.02
32,Tripura,2.133333,154305.000000,5.931351,0.06
33,Uttar Pradesh,2.766667,86022.333333,6.295405,0.10
34,Uttarakhand,5.533333,220232.666667,5.594865,0.04
35,West Bengal,2.766667,136769.000000,5.483514,0.05